# Background reconstruction for NotesRadiationCoupling_DONTTOUCH.pdf Fig. 1, model 2.

output =
lensing = no
a_ini_over_a_today_default = 1.e-13

h = 0.7
Omega_k = 0.

Omega_g = 1.e-12
Omega_ur = 0.
N_ncdm =
xi_idr = 103.39463079143411
YHe = 0.24
recombination = RECFAST

Omega_b = 1.e-12
Omega_cdm = 0.
Omega_qcdm = 0.3149

Omega_Lambda = 0.
Omega_fld = 0.
Omega_scf = -1

scf_potential = exp
scf_lambda = 1.6329931618554521
scf_V0 = 0.7

scf_coupling_type = conformal
scf_conformal_form = matter_exp
scf_allow_multiple_couplings = yes
scf_interacting_radiation = yes
scf_ic_from_today = yes

scf_C0 = -0.0625
scf_beta = -0.6123724356957945
scf_alpha = 0.
scf_D0 = 0.

scf_C0_r = -0.02
scf_beta_r = 1.

attractor_ic_scf = no
scf_phi_today = 0.
scf_w_phi_today = -0.59422361340
scf_phi_prime_today_sign = 1.

write_background = yes
write_parameters = yes
write_warnings = yes
headers = yes
format = class
root = output/notes_fig1_model2
overwrite_root = yes

input_verbose = 1
background_verbose = 2
thermodynamics_verbose = 0
perturbations_verbose = 0
transfer_verbose = 0
primordial_verbose = 0
harmonic_verbose = 0
fourier_verbose = 0
lensing_verbose = 0
distortions_verbose = 0
output_verbose = 1
